import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="description" content="Free Web tutorials" />
        <meta name="keywords" content="HTML, CSS, JavaScript" />
        <meta name="author" content="John Doe" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* open graph coisa para compartilhamento da W3C*/}
        <meta property="og:title" content="" />
        <meta property="og:image" content="URL da imagem" />
        <meta property="og:description" content="" />
        <meta property="og:url" content="URL da Rede Social" />
      </Head>
      <body>
        <nav>
          <Link href="/"></Link>
          <Link href="/about"></Link>
        </nav>
        <header></header>
        <main>{children}</main>
        <footer>
          <p></p>
        </footer>
      </body>
    </html>
  );
}
